<?php
/**
 * This file is part of the "Docalist Core" plugin.
 *
 * Copyright (C) 2012, 2013 Daniel Ménard
 *
 * For copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 *
 * @package     Docalist
 * @subpackage  Tables
 * @author      Daniel Ménard <daniel.menard@laposte.net>
 * @version     SVN: $Id$
 */

/*
 * Liste des pays, en français
 * Adapté de http://fr.wikipedia.org/wiki/ISO_3166-1
 *
 * 2013-04-09 Version initiale
 * 2013-09-27 Mise au format docalist. 249 pays.
 * 2013-11-03 Renomme 'alpha3' et 'name' en 'code' et 'label'.
 * 2014-02-18 Simplification de la table. Change l'ordre des champs (c'est le
 * code 2 lettres qui est le code de référence), trie la table par codes.
 * Suppresion du code numérique. Utilise les mêmes noms de champs que pour la
 * table des langues.
 */

return [
    ['code', 'alpha3', 'label'],

    ['AD', 'AND', __('Andorre', 'docalist-core')],
    ['AE', 'ARE', __('Émirats arabes unis', 'docalist-core')],
    ['AF', 'AFG', __('Afghanistan', 'docalist-core')],
    ['AG', 'ATG', __('Antigua-et-Barbuda', 'docalist-core')],
    ['AI', 'AIA', __('Anguilla', 'docalist-core')],
    ['AL', 'ALB', __('Albanie', 'docalist-core')],
    ['AM', 'ARM', __('Arménie', 'docalist-core')],
    ['AO', 'AGO', __('Angola', 'docalist-core')],
    ['AQ', 'ATA', __('Antarctique', 'docalist-core')],
    ['AR', 'ARG', __('Argentine', 'docalist-core')],
    ['AS', 'ASM', __('Samoa américaines', 'docalist-core')],
    ['AT', 'AUT', __('Autriche', 'docalist-core')],
    ['AU', 'AUS', __('Australie', 'docalist-core')],
    ['AW', 'ABW', __('Aruba', 'docalist-core')],
    ['AX', 'ALA', __('Îles Åland', 'docalist-core')],
    ['AZ', 'AZE', __('Azerbaïdjan', 'docalist-core')],
    ['BA', 'BIH', __('Bosnie-Herzégovine', 'docalist-core')],
    ['BB', 'BRB', __('Barbade', 'docalist-core')],
    ['BD', 'BGD', __('Bangladesh', 'docalist-core')],
    ['BE', 'BEL', __('Belgique', 'docalist-core')],
    ['BF', 'BFA', __('Burkina Faso', 'docalist-core')],
    ['BG', 'BGR', __('Bulgarie', 'docalist-core')],
    ['BH', 'BHR', __('Bahreïn', 'docalist-core')],
    ['BI', 'BDI', __('Burundi', 'docalist-core')],
    ['BJ', 'BEN', __('Bénin', 'docalist-core')],
    ['BL', 'BLM', __('Saint-Barthélemy', 'docalist-core')],
    ['BM', 'BMU', __('Bermudes', 'docalist-core')],
    ['BN', 'BRN', __('Brunei', 'docalist-core')],
    ['BO', 'BOL', __('Bolivie', 'docalist-core')],
    ['BQ', 'BES', __('Pays-Bas caribéens', 'docalist-core')],
    ['BR', 'BRA', __('Brésil', 'docalist-core')],
    ['BS', 'BHS', __('Bahamas', 'docalist-core')],
    ['BT', 'BTN', __('Bhoutan', 'docalist-core')],
    ['BV', 'BVT', __('Île Bouvet', 'docalist-core')],
    ['BW', 'BWA', __('Botswana', 'docalist-core')],
    ['BY', 'BLR', __('Biélorussie', 'docalist-core')],
    ['BZ', 'BLZ', __('Belize', 'docalist-core')],
    ['CA', 'CAN', __('Canada', 'docalist-core')],
    ['CC', 'CCK', __('Îles Cocos', 'docalist-core')],
    ['CD', 'COD', __('République démocratique du Congo', 'docalist-core')],
    ['CF', 'CAF', __('République centrafricaine', 'docalist-core')],
    ['CG', 'COG', __('République du Congo', 'docalist-core')],
    ['CH', 'CHE', __('Suisse', 'docalist-core')],
    ['CI', 'CIV', __('Côte d\'Ivoire', 'docalist-core')],
    ['CK', 'COK', __('Îles Cook', 'docalist-core')],
    ['CL', 'CHL', __('Chili', 'docalist-core')],
    ['CM', 'CMR', __('Cameroun', 'docalist-core')],
    ['CN', 'CHN', __('Chine', 'docalist-core')],
    ['CO', 'COL', __('Colombie', 'docalist-core')],
    ['CR', 'CRI', __('Costa Rica', 'docalist-core')],
    ['CU', 'CUB', __('Cuba', 'docalist-core')],
    ['CV', 'CPV', __('Cap-Vert', 'docalist-core')],
    ['CW', 'CUW', __('Curaçao', 'docalist-core')],
    ['CX', 'CXR', __('Île Christmas', 'docalist-core')],
    ['CY', 'CYP', __('Chypre', 'docalist-core')],
    ['CZ', 'CZE', __('République tchèque', 'docalist-core')],
    ['DE', 'DEU', __('Allemagne', 'docalist-core')],
    ['DJ', 'DJI', __('Djibouti', 'docalist-core')],
    ['DK', 'DNK', __('Danemark', 'docalist-core')],
    ['DM', 'DMA', __('Dominique', 'docalist-core')],
    ['DO', 'DOM', __('République dominicaine', 'docalist-core')],
    ['DZ', 'DZA', __('Algérie', 'docalist-core')],
    ['EC', 'ECU', __('Équateur', 'docalist-core')],
    ['EE', 'EST', __('Estonie', 'docalist-core')],
    ['EG', 'EGY', __('Égypte', 'docalist-core')],
    ['EH', 'ESH', __('République arabe sahraouie démocratique', 'docalist-core')],
    ['ER', 'ERI', __('Érythrée', 'docalist-core')],
    ['ES', 'ESP', __('Espagne', 'docalist-core')],
    ['ET', 'ETH', __('Éthiopie', 'docalist-core')],
    ['FI', 'FIN', __('Finlande', 'docalist-core')],
    ['FJ', 'FJI', __('Fidji', 'docalist-core')],
    ['FK', 'FLK', __('Malouines', 'docalist-core')],
    ['FM', 'FSM', __('Micronésie', 'docalist-core')],
    ['FO', 'FRO', __('Îles Féroé', 'docalist-core')],
    ['FR', 'FRA', __('France', 'docalist-core')],
    ['GA', 'GAB', __('Gabon', 'docalist-core')],
    ['GB', 'GBR', __('Royaume-Uni', 'docalist-core')],
    ['GD', 'GRD', __('Grenade', 'docalist-core')],
    ['GE', 'GEO', __('Géorgie', 'docalist-core')],
    ['GF', 'GUF', __('Guyane', 'docalist-core')],
    ['GG', 'GGY', __('Guernesey', 'docalist-core')],
    ['GH', 'GHA', __('Ghana', 'docalist-core')],
    ['GI', 'GIB', __('Gibraltar', 'docalist-core')],
    ['GL', 'GRL', __('Groenland', 'docalist-core')],
    ['GM', 'GMB', __('Gambie', 'docalist-core')],
    ['GN', 'GIN', __('Guinée', 'docalist-core')],
    ['GP', 'GLP', __('Guadeloupe', 'docalist-core')],
    ['GQ', 'GNQ', __('Guinée équatoriale', 'docalist-core')],
    ['GR', 'GRC', __('Grèce', 'docalist-core')],
    ['GS', 'SGS', __('Géorgie du Sud-et-les Îles Sandwich du Sud', 'docalist-core')],
    ['GT', 'GTM', __('Guatemala', 'docalist-core')],
    ['GU', 'GUM', __('Guam', 'docalist-core')],
    ['GW', 'GNB', __('Guinée-Bissau', 'docalist-core')],
    ['GY', 'GUY', __('Guyana', 'docalist-core')],
    ['HK', 'HKG', __('Hong Kong', 'docalist-core')],
    ['HM', 'HMD', __('Îles Heard-et-MacDonald', 'docalist-core')],
    ['HN', 'HND', __('Honduras', 'docalist-core')],
    ['HR', 'HRV', __('Croatie', 'docalist-core')],
    ['HT', 'HTI', __('Haïti', 'docalist-core')],
    ['HU', 'HUN', __('Hongrie', 'docalist-core')],
    ['ID', 'IDN', __('Indonésie', 'docalist-core')],
    ['IE', 'IRL', __('Irlande', 'docalist-core')],
    ['IL', 'ISR', __('Israël', 'docalist-core')],
    ['IM', 'IMN', __('Île de Man', 'docalist-core')],
    ['IN', 'IND', __('Inde', 'docalist-core')],
    ['IO', 'IOT', __('Territoire britannique de l\'océan Indien', 'docalist-core')],
    ['IQ', 'IRQ', __('Irak', 'docalist-core')],
    ['IR', 'IRN', __('Iran', 'docalist-core')],
    ['IS', 'ISL', __('Islande', 'docalist-core')],
    ['IT', 'ITA', __('Italie', 'docalist-core')],
    ['JE', 'JEY', __('Jersey', 'docalist-core')],
    ['JM', 'JAM', __('Jamaïque', 'docalist-core')],
    ['JO', 'JOR', __('Jordanie', 'docalist-core')],
    ['JP', 'JPN', __('Japon', 'docalist-core')],
    ['KE', 'KEN', __('Kenya', 'docalist-core')],
    ['KG', 'KGZ', __('Kirghizistan', 'docalist-core')],
    ['KH', 'KHM', __('Cambodge', 'docalist-core')],
    ['KI', 'KIR', __('Kiribati', 'docalist-core')],
    ['KM', 'COM', __('Comores', 'docalist-core')],
    ['KN', 'KNA', __('Saint-Christophe-et-Niévès', 'docalist-core')],
    ['KP', 'PRK', __('Corée du Nord', 'docalist-core')],
    ['KR', 'KOR', __('Corée du Sud', 'docalist-core')],
    ['KW', 'KWT', __('Koweït', 'docalist-core')],
    ['KY', 'CYM', __('Îles Caïmans', 'docalist-core')],
    ['KZ', 'KAZ', __('Kazakhstan', 'docalist-core')],
    ['LA', 'LAO', __('Laos', 'docalist-core')],
    ['LB', 'LBN', __('Liban', 'docalist-core')],
    ['LC', 'LCA', __('Sainte-Lucie', 'docalist-core')],
    ['LI', 'LIE', __('Liechtenstein', 'docalist-core')],
    ['LK', 'LKA', __('Sri Lanka', 'docalist-core')],
    ['LR', 'LBR', __('Liberia', 'docalist-core')],
    ['LS', 'LSO', __('Lesotho', 'docalist-core')],
    ['LT', 'LTU', __('Lituanie', 'docalist-core')],
    ['LU', 'LUX', __('Luxembourg', 'docalist-core')],
    ['LV', 'LVA', __('Lettonie', 'docalist-core')],
    ['LY', 'LBY', __('Libye', 'docalist-core')],
    ['MA', 'MAR', __('Maroc', 'docalist-core')],
    ['MC', 'MCO', __('Monaco', 'docalist-core')],
    ['MD', 'MDA', __('Moldavie', 'docalist-core')],
    ['ME', 'MNE', __('Monténégro', 'docalist-core')],
    ['MF', 'MAF', __('Saint-Martin', 'docalist-core')],
    ['MG', 'MDG', __('Madagascar', 'docalist-core')],
    ['MH', 'MHL', __('Marshall', 'docalist-core')],
    ['MK', 'MKD', __('Macédoine', 'docalist-core')],
    ['ML', 'MLI', __('Mali', 'docalist-core')],
    ['MM', 'MMR', __('Birmanie', 'docalist-core')],
    ['MN', 'MNG', __('Mongolie', 'docalist-core')],
    ['MO', 'MAC', __('Macao', 'docalist-core')],
    ['MP', 'MNP', __('Îles Mariannes du Nord', 'docalist-core')],
    ['MQ', 'MTQ', __('Martinique', 'docalist-core')],
    ['MR', 'MRT', __('Mauritanie', 'docalist-core')],
    ['MS', 'MSR', __('Montserrat', 'docalist-core')],
    ['MT', 'MLT', __('Malte', 'docalist-core')],
    ['MU', 'MUS', __('Maurice', 'docalist-core')],
    ['MV', 'MDV', __('Maldives', 'docalist-core')],
    ['MW', 'MWI', __('Malawi', 'docalist-core')],
    ['MX', 'MEX', __('Mexique', 'docalist-core')],
    ['MY', 'MYS', __('Malaisie', 'docalist-core')],
    ['MZ', 'MOZ', __('Mozambique', 'docalist-core')],
    ['NA', 'NAM', __('Namibie', 'docalist-core')],
    ['NC', 'NCL', __('Nouvelle-Calédonie', 'docalist-core')],
    ['NE', 'NER', __('Niger', 'docalist-core')],
    ['NF', 'NFK', __('Île Norfolk', 'docalist-core')],
    ['NG', 'NGA', __('Nigeria', 'docalist-core')],
    ['NI', 'NIC', __('Nicaragua', 'docalist-core')],
    ['NL', 'NLD', __('Pays-Bas', 'docalist-core')],
    ['NO', 'NOR', __('Norvège', 'docalist-core')],
    ['NP', 'NPL', __('Népal', 'docalist-core')],
    ['NR', 'NRU', __('Nauru', 'docalist-core')],
    ['NU', 'NIU', __('Niue', 'docalist-core')],
    ['NZ', 'NZL', __('Nouvelle-Zélande', 'docalist-core')],
    ['OM', 'OMN', __('Oman', 'docalist-core')],
    ['PA', 'PAN', __('Panama', 'docalist-core')],
    ['PE', 'PER', __('Pérou', 'docalist-core')],
    ['PF', 'PYF', __('Polynésie française', 'docalist-core')],
    ['PG', 'PNG', __('Papouasie-Nouvelle-Guinée', 'docalist-core')],
    ['PH', 'PHL', __('Philippines', 'docalist-core')],
    ['PK', 'PAK', __('Pakistan', 'docalist-core')],
    ['PL', 'POL', __('Pologne', 'docalist-core')],
    ['PM', 'SPM', __('Saint-Pierre-et-Miquelon', 'docalist-core')],
    ['PN', 'PCN', __('Îles Pitcairn', 'docalist-core')],
    ['PR', 'PRI', __('Porto Rico', 'docalist-core')],
    ['PS', 'PSE', __('Palestine', 'docalist-core')],
    ['PT', 'PRT', __('Portugal', 'docalist-core')],
    ['PW', 'PLW', __('Palaos', 'docalist-core')],
    ['PY', 'PRY', __('Paraguay', 'docalist-core')],
    ['QA', 'QAT', __('Qatar', 'docalist-core')],
    ['RE', 'REU', __('La Réunion', 'docalist-core')],
    ['RO', 'ROU', __('Roumanie', 'docalist-core')],
    ['RS', 'SRB', __('Serbie', 'docalist-core')],
    ['RU', 'RUS', __('Russie', 'docalist-core')],
    ['RW', 'RWA', __('Rwanda', 'docalist-core')],
    ['SA', 'SAU', __('Arabie saoudite', 'docalist-core')],
    ['SB', 'SLB', __('Salomon', 'docalist-core')],
    ['SC', 'SYC', __('Seychelles', 'docalist-core')],
    ['SD', 'SDN', __('Soudan', 'docalist-core')],
    ['SE', 'SWE', __('Suède', 'docalist-core')],
    ['SG', 'SGP', __('Singapour', 'docalist-core')],
    ['SH', 'SHN', __('Sainte-Hélène, Ascension et Tristan da Cunha', 'docalist-core')],
    ['SI', 'SVN', __('Slovénie', 'docalist-core')],
    ['SJ', 'SJM', __('Svalbard et île Jan Mayen', 'docalist-core')],
    ['SK', 'SVK', __('Slovaquie', 'docalist-core')],
    ['SL', 'SLE', __('Sierra Leone', 'docalist-core')],
    ['SM', 'SMR', __('Saint-Marin', 'docalist-core')],
    ['SN', 'SEN', __('Sénégal', 'docalist-core')],
    ['SO', 'SOM', __('Somalie', 'docalist-core')],
    ['SR', 'SUR', __('Suriname', 'docalist-core')],
    ['SS', 'SSD', __('Soudan du Sud', 'docalist-core')],
    ['ST', 'STP', __('Sao Tomé-et-Principe', 'docalist-core')],
    ['SV', 'SLV', __('Salvador', 'docalist-core')],
    ['SX', 'SXM', __('Sint Maarten', 'docalist-core')],
    ['SY', 'SYR', __('Syrie', 'docalist-core')],
    ['SZ', 'SWZ', __('Swaziland', 'docalist-core')],
    ['TC', 'TCA', __('Îles Turques-et-Caïques', 'docalist-core')],
    ['TD', 'TCD', __('Tchad', 'docalist-core')],
    ['TF', 'ATF', __('Terres australes et antarctiques françaises', 'docalist-core')],
    ['TG', 'TGO', __('Togo', 'docalist-core')],
    ['TH', 'THA', __('Thaïlande', 'docalist-core')],
    ['TJ', 'TJK', __('Tadjikistan', 'docalist-core')],
    ['TK', 'TKL', __('Tokelau', 'docalist-core')],
    ['TL', 'TLS', __('Timor oriental', 'docalist-core')],
    ['TM', 'TKM', __('Turkménistan', 'docalist-core')],
    ['TN', 'TUN', __('Tunisie', 'docalist-core')],
    ['TO', 'TON', __('Tonga', 'docalist-core')],
    ['TR', 'TUR', __('Turquie', 'docalist-core')],
    ['TT', 'TTO', __('Trinité-et-Tobago', 'docalist-core')],
    ['TV', 'TUV', __('Tuvalu', 'docalist-core')],
    ['TW', 'TWN', __('Taïwan', 'docalist-core')],
    ['TZ', 'TZA', __('Tanzanie', 'docalist-core')],
    ['UA', 'UKR', __('Ukraine', 'docalist-core')],
    ['UG', 'UGA', __('Ouganda', 'docalist-core')],
    ['UM', 'UMI', __('Îles mineures éloignées des États-Unis', 'docalist-core')],
    ['US', 'USA', __('États-Unis', 'docalist-core')],
    ['UY', 'URY', __('Uruguay', 'docalist-core')],
    ['UZ', 'UZB', __('Ouzbékistan', 'docalist-core')],
    ['VA', 'VAT', __('Vatican', 'docalist-core')],
    ['VC', 'VCT', __('Saint-Vincent-et-les-Grenadines', 'docalist-core')],
    ['VE', 'VEN', __('Venezuela', 'docalist-core')],
    ['VG', 'VGB', __('Îles Vierges britanniques', 'docalist-core')],
    ['VI', 'VIR', __('Îles Vierges des États-Unis', 'docalist-core')],
    ['VN', 'VNM', __('Viêt Nam', 'docalist-core')],
    ['VU', 'VUT', __('Vanuatu', 'docalist-core')],
    ['WF', 'WLF', __('Wallis-et-Futuna', 'docalist-core')],
    ['WS', 'WSM', __('Samoa', 'docalist-core')],
    ['YE', 'YEM', __('Yémen', 'docalist-core')],
    ['YT', 'MYT', __('Mayotte', 'docalist-core')],
    ['ZA', 'ZAF', __('Afrique du Sud', 'docalist-core')],
    ['ZM', 'ZMB', __('Zambie', 'docalist-core')],
    ['ZW', 'ZWE', __('Zimbabwe', 'docalist-core')],
];