<?php
/**
 * This file is part of the "Docalist Core" plugin.
 *
 * Copyright (C) 2012-2014 Daniel Ménard
 *
 * For copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 *
 * @package     Docalist
 * @subpackage  Tables
 * @author      Daniel Ménard <daniel.menard@laposte.net>
 * @version     SVN: $Id$
 */

/*
 * Liste des langues, en français
 * Adapté de : http://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1
 *
 * 2013-04-09 Version initiale
 * 2013-09-27 Mise au format docalist. 538 langues.
 * 2014-02-18 Simplification : on ne garde que les langues qui ont un
 * code ISO 2 lettres (185 langues). Change l'ordre des champs (c'est le
 * code 2 lettres qui est le code de référence), trie la table par codes.
 */

return [
    ['code', 'alpha3', 'label'],

    ['aa', 'aar', __('afar', 'docalist-core')],
    ['ab', 'abk', __('abkhaze', 'docalist-core')],
    ['ae', 'ave', __('avestique', 'docalist-core')],
    ['af', 'afr', __('afrikaans', 'docalist-core')],
    ['ak', 'aka', __('akan', 'docalist-core')],
    ['am', 'amh', __('amharique', 'docalist-core')],
    ['an', 'arg', __('aragonais', 'docalist-core')],
    ['ar', 'ara', __('arabe', 'docalist-core')],
    ['as', 'asm', __('assamais', 'docalist-core')],
    ['av', 'ava', __('avar', 'docalist-core')],
    ['ay', 'aym', __('aymara', 'docalist-core')],
    ['az', 'aze', __('azéri', 'docalist-core')],
    ['ba', 'bak', __('bachkir', 'docalist-core')],
    ['be', 'bel', __('biélorusse', 'docalist-core')],
    ['bg', 'bul', __('bulgare', 'docalist-core')],
    ['bh', 'bih', __('bihari', 'docalist-core')],
    ['bi', 'bis', __('bichelamar', 'docalist-core')],
    ['bm', 'bam', __('bambara', 'docalist-core')],
    ['bn', 'ben', __('bengali', 'docalist-core')],
    ['bo', 'tib', __('tibétain', 'docalist-core')],
    ['br', 'bre', __('breton', 'docalist-core')],
    ['bs', 'bos', __('bosnien', 'docalist-core')],
    ['ca', 'cat', __('catalan', 'docalist-core')],
    ['ce', 'che', __('tchétchène', 'docalist-core')],
    ['ch', 'cha', __('chamorro', 'docalist-core')],
    ['co', 'cos', __('corse', 'docalist-core')],
    ['cr', 'cre', __('cri', 'docalist-core')],
    ['cs', 'cze', __('tchèque', 'docalist-core')],
    ['cu', 'chu', __('vieux slave', 'docalist-core')],
    ['cv', 'chv', __('tchouvache', 'docalist-core')],
    ['cy', 'wel', __('gallois', 'docalist-core')],
    ['da', 'dan', __('danois', 'docalist-core')],
    ['de', 'ger', __('allemand', 'docalist-core')],
    ['dv', 'div', __('dhivehi', 'docalist-core')],
    ['dz', 'dzo', __('dzongkha', 'docalist-core')],
    ['ee', 'ewe', __('éwé', 'docalist-core')],
    ['el', 'gre', __('grec moderne', 'docalist-core')],
    ['en', 'eng', __('anglais', 'docalist-core')],
    ['eo', 'epo', __('espéranto', 'docalist-core')],
    ['es', 'spa', __('espagnol', 'docalist-core')],
    ['et', 'est', __('estonien', 'docalist-core')],
    ['eu', 'baq', __('basque', 'docalist-core')],
    ['fa', 'per', __('persan', 'docalist-core')],
    ['ff', 'ful', __('peul', 'docalist-core')],
    ['fi', 'fin', __('finnois', 'docalist-core')],
    ['fj', 'fij', __('fidjien', 'docalist-core')],
    ['fo', 'fao', __('féringien', 'docalist-core')],
    ['fr', 'fre', __('français', 'docalist-core')],
    ['fy', 'fry', __('frison', 'docalist-core')],
    ['ga', 'gle', __('irlandais', 'docalist-core')],
    ['gd', 'gla', __('écossais', 'docalist-core')],
    ['gl', 'glg', __('galicien', 'docalist-core')],
    ['gn', 'grn', __('guarani', 'docalist-core')],
    ['gu', 'guj', __('gujarâtî', 'docalist-core')],
    ['gv', 'glv', __('mannois', 'docalist-core')],
    ['ha', 'hau', __('haoussa', 'docalist-core')],
    ['he', 'heb', __('hébreu', 'docalist-core')],
    ['hi', 'hin', __('hindî', 'docalist-core')],
    ['ho', 'hmo', __('hiri motu', 'docalist-core')],
    ['hr', 'hrv', __('croate', 'docalist-core')],
    ['ht', 'hat', __('créole haïtien', 'docalist-core')],
    ['hu', 'hun', __('hongrois', 'docalist-core')],
    ['hy', 'arm', __('arménien', 'docalist-core')],
    ['hz', 'her', __('herero', 'docalist-core')],
    ['ia', 'ina', __('interlingua', 'docalist-core')],
    ['id', 'ind', __('indonésien', 'docalist-core')],
    ['ie', 'ile', __('occidental', 'docalist-core')],
    ['ig', 'ibo', __('igbo', 'docalist-core')],
    ['ii', 'iii', __('yi', 'docalist-core')],
    ['ik', 'ipk', __('inupiaq', 'docalist-core')],
    ['io', 'ido', __('ido', 'docalist-core')],
    ['is', 'ice', __('islandais', 'docalist-core')],
    ['it', 'ita', __('italien', 'docalist-core')],
    ['iu', 'iku', __('inuktitut', 'docalist-core')],
    ['ja', 'jpn', __('japonais', 'docalist-core')],
    ['jv', 'jav', __('javanais', 'docalist-core')],
    ['ka', 'geo', __('géorgien', 'docalist-core')],
    ['kg', 'kon', __('kikongo', 'docalist-core')],
    ['ki', 'kik', __('kikuyu', 'docalist-core')],
    ['kj', 'kua', __('kuanyama', 'docalist-core')],
    ['kk', 'kaz', __('kazakh', 'docalist-core')],
    ['kl', 'kal', __('kalaallisut', 'docalist-core')],
    ['km', 'khm', __('khmer', 'docalist-core')],
    ['kn', 'kan', __('kannara', 'docalist-core')],
    ['ko', 'kor', __('coréen', 'docalist-core')],
    ['kr', 'kau', __('kanouri', 'docalist-core')],
    ['ks', 'kas', __('kashmiri', 'docalist-core')],
    ['ku', 'kur', __('kurde', 'docalist-core')],
    ['kv', 'kom', __('komi', 'docalist-core')],
    ['kw', 'cor', __('cornique', 'docalist-core')],
    ['ky', 'kir', __('kirghiz', 'docalist-core')],
    ['la', 'lat', __('latin', 'docalist-core')],
    ['lb', 'ltz', __('luxembourgeois', 'docalist-core')],
    ['lg', 'lug', __('ganda', 'docalist-core')],
    ['li', 'lim', __('limbourgeois', 'docalist-core')],
    ['ln', 'lin', __('lingala', 'docalist-core')],
    ['lo', 'lao', __('lao', 'docalist-core')],
    ['lt', 'lit', __('lituanien', 'docalist-core')],
    ['lu', 'lub', __('luba-katanga', 'docalist-core')],
    ['lv', 'lav', __('letton', 'docalist-core')],
    ['mg', 'mlg', __('malgache', 'docalist-core')],
    ['mh', 'mah', __('marshallais', 'docalist-core')],
    ['mi', 'mao', __('maori', 'docalist-core')],
    ['mk', 'mac', __('macédonien', 'docalist-core')],
    ['ml', 'mal', __('malayalam', 'docalist-core')],
    ['mn', 'mon', __('mongol', 'docalist-core')],
    ['mo', 'mol', __('moldave', 'docalist-core')],
    ['mr', 'mar', __('marâthî', 'docalist-core')],
    ['ms', 'may', __('malais', 'docalist-core')],
    ['mt', 'mlt', __('maltais', 'docalist-core')],
    ['my', 'bur', __('birman', 'docalist-core')],
    ['na', 'nau', __('nauruan', 'docalist-core')],
    ['nb', 'nob', __('norvégien bokmål', 'docalist-core')],
    ['nd', 'nde', __('ndébélé du nord', 'docalist-core')],
    ['ne', 'nep', __('népalais', 'docalist-core')],
    ['ng', 'ndo', __('ndonga', 'docalist-core')],
    ['nl', 'dut', __('néerlandais', 'docalist-core')],
    ['nn', 'nno', __('norvégien nynorsk', 'docalist-core')],
    ['no', 'nor', __('norvégien', 'docalist-core')],
    ['nr', 'nbl', __('ndébélé du sud', 'docalist-core')],
    ['nv', 'nav', __('navajo', 'docalist-core')],
    ['ny', 'nya', __('chichewa', 'docalist-core')],
    ['oc', 'oci', __('occitan', 'docalist-core')],
    ['oj', 'oji', __('ojibwé', 'docalist-core')],
    ['om', 'orm', __('oromo', 'docalist-core')],
    ['or', 'ori', __('oriya', 'docalist-core')],
    ['os', 'oss', __('ossète', 'docalist-core')],
    ['pa', 'pan', __('penjâbî', 'docalist-core')],
    ['pi', 'pli', __('pali', 'docalist-core')],
    ['pl', 'pol', __('polonais', 'docalist-core')],
    ['ps', 'pus', __('pachto', 'docalist-core')],
    ['pt', 'por', __('portugais', 'docalist-core')],
    ['qu', 'que', __('quechua', 'docalist-core')],
    ['rm', 'roh', __('romanche', 'docalist-core')],
    ['rn', 'run', __('kirundi', 'docalist-core')],
    ['ro', 'rum', __('roumain', 'docalist-core')],
    ['ru', 'rus', __('russe', 'docalist-core')],
    ['rw', 'kin', __('kinyarwanda', 'docalist-core')],
    ['sa', 'san', __('sanskrit', 'docalist-core')],
    ['sc', 'srd', __('sarde', 'docalist-core')],
    ['sd', 'snd', __('sindhi', 'docalist-core')],
    ['se', 'sme', __('same du nord', 'docalist-core')],
    ['sg', 'sag', __('sango', 'docalist-core')],
    ['si', 'sin', __('cingalais', 'docalist-core')],
    ['sk', 'slo', __('slovaque', 'docalist-core')],
    ['sl', 'slv', __('slovène', 'docalist-core')],
    ['sm', 'smo', __('samoan', 'docalist-core')],
    ['sn', 'sna', __('shona', 'docalist-core')],
    ['so', 'som', __('somali', 'docalist-core')],
    ['sq', 'alb', __('albanais', 'docalist-core')],
    ['sr', 'srp', __('serbe', 'docalist-core')],
    ['ss', 'ssw', __('siswati', 'docalist-core')],
    ['st', 'sot', __('sotho du sud', 'docalist-core')],
    ['su', 'sun', __('soundanais', 'docalist-core')],
    ['sv', 'swe', __('suédois', 'docalist-core')],
    ['sw', 'swa', __('swahili', 'docalist-core')],
    ['ta', 'tam', __('tamoul', 'docalist-core')],
    ['te', 'tel', __('télougou', 'docalist-core')],
    ['tg', 'tgk', __('tadjik', 'docalist-core')],
    ['th', 'tha', __('thaï', 'docalist-core')],
    ['ti', 'tir', __('tigrinya', 'docalist-core')],
    ['tk', 'tuk', __('turkmène', 'docalist-core')],
    ['tl', 'tgl', __('tagalog', 'docalist-core')],
    ['tn', 'tsn', __('tswana', 'docalist-core')],
    ['to', 'ton', __('tongien', 'docalist-core')],
    ['tr', 'tur', __('turc', 'docalist-core')],
    ['ts', 'tso', __('tsonga', 'docalist-core')],
    ['tt', 'tat', __('tatar', 'docalist-core')],
    ['tw', 'twi', __('twi', 'docalist-core')],
    ['ty', 'tah', __('tahitien', 'docalist-core')],
    ['ug', 'uig', __('ouïghour', 'docalist-core')],
    ['uk', 'ukr', __('ukrainien', 'docalist-core')],
    ['ur', 'urd', __('ourdou', 'docalist-core')],
    ['uz', 'uzb', __('ouzbek', 'docalist-core')],
    ['ve', 'ven', __('venda', 'docalist-core')],
    ['vi', 'vie', __('vietnamien', 'docalist-core')],
    ['vo', 'vol', __('volapük', 'docalist-core')],
    ['wa', 'wln', __('wallon', 'docalist-core')],
    ['wo', 'wol', __('wolof', 'docalist-core')],
    ['xh', 'xho', __('xhosa', 'docalist-core')],
    ['yi', 'yid', __('yiddish', 'docalist-core')],
    ['yo', 'yor', __('yoruba', 'docalist-core')],
    ['za', 'zha', __('zhuang', 'docalist-core')],
    ['zh', 'chi', __('chinois', 'docalist-core')],
    ['zu', 'zul', __('zoulou', 'docalist-core')],
];